#include <iostream>
using namespace std;

// Declare the lexer function generated by FLEX
extern int yylex();
extern FILE* yyin;

int main() {
    // Open source code file
    yyin = fopen("input.txt", "r");
    if (!yyin) {
        cerr << "Error opening input file." << endl;
        return 1;
    }

    // Call lexer
    yylex();

    fclose(yyin);
    return 0;
}
